version: "3.5"
services:
  db:
    image: mysql:8.0.40
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    command:
      - --default_authentication_plugin=mysql_native_password
      - --binlog-format=ROW
      - --server-id=1
    ports:
      - "13366:3306"