// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"awesome-shortLink/internal/repository"
	"awesome-shortLink/internal/repository/cache"
	"awesome-shortLink/internal/repository/dao"
	"awesome-shortLink/internal/repository/filter"
	"awesome-shortLink/internal/service"
	"awesome-shortLink/internal/web"
	"awesome-shortLink/ioc"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitShortLinkHdl() *web.ShortLinkHandler {
	db := ioc.InitDB()
	shortLinkDAO := dao.NewShortLinkDAOV1(db)
	logger := ioc.InitZap()
	cmdable := ioc.InitRedis()
	shortLinkCache := cache.NewShortLinkRedisV1(cmdable)
	bloomFilter := filter.NewBloomFilterV1(cmdable)
	node := ioc.InitSnowFlakeNode()
	shortLinkRepository := repository.NewShortLinkRepositoryV3(shortLinkDAO, logger, shortLinkCache, bloomFilter, node)
	shortLinkService := service.NewShortLinkServiceBasic(shortLinkRepository, logger)
	shortLinkHandler := web.NewShortLinkHandler(shortLinkService, logger)
	return shortLinkHandler
}

func InitWebServer() *gin.Engine {
	shortLinkHandler := InitShortLinkHdl()
	v := ioc.InitMiddleWare()
	engine := ioc.InitGinEngine(shortLinkHandler, v...)
	return engine
}
